/**
 * Copyright (c) Christine Abernathy.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

export const bookMap: { [key: string]: { id: number; abbreviation: string } } =
  {
    Genesis: { id: 1, abbreviation: 'GEN' },
    Exodus: { id: 2, abbreviation: 'EXO' },
    Leviticus: { id: 3, abbreviation: 'LEV' },
    Numbers: { id: 4, abbreviation: 'NUM' },
    Deuteronomy: { id: 5, abbreviation: 'DEU' },
    Joshua: { id: 6, abbreviation: 'JOS' },
    Judges: { id: 7, abbreviation: 'JDG' },
    Ruth: { id: 8, abbreviation: 'RUT' },
    '1 Samuel': { id: 9, abbreviation: '1SA' },
    '2 Samuel': { id: 10, abbreviation: '2SA' },
    '1 Kings': { id: 11, abbreviation: '1KI' },
    '2 Kings': { id: 12, abbreviation: '2KI' },
    '1 Chronicles': { id: 13, abbreviation: '1CH' },
    '2 Chronicles': { id: 14, abbreviation: '2CH' },
    Ezra: { id: 15, abbreviation: 'EZR' },
    Nehemiah: { id: 16, abbreviation: 'NEH' },
    Esther: { id: 17, abbreviation: 'EST' },
    Job: { id: 18, abbreviation: 'JOB' },
    Psalms: { id: 19, abbreviation: 'PSA' },
    Psalm: { id: 19, abbreviation: 'PSA' },
    Proverbs: { id: 20, abbreviation: 'PRO' },
    Ecclesiastes: { id: 21, abbreviation: 'ECC' },
    'Song of Solomon': { id: 22, abbreviation: 'SNG' },
    Isaiah: { id: 23, abbreviation: 'ISA' },
    Jeremiah: { id: 24, abbreviation: 'JER' },
    Lamentations: { id: 25, abbreviation: 'LAM' },
    Ezekiel: { id: 26, abbreviation: 'EZK' },
    Daniel: { id: 27, abbreviation: 'DAN' },
    Hosea: { id: 28, abbreviation: 'HOS' },
    Joel: { id: 29, abbreviation: 'JOL' },
    Amos: { id: 30, abbreviation: 'AMO' },
    Obadiah: { id: 31, abbreviation: 'OBA' },
    Jonah: { id: 32, abbreviation: 'JON' },
    Micah: { id: 33, abbreviation: 'MIC' },
    Nahum: { id: 34, abbreviation: 'NAM' },
    Habakkuk: { id: 35, abbreviation: 'HAB' },
    Zephaniah: { id: 36, abbreviation: 'ZEP' },
    Haggai: { id: 37, abbreviation: 'HAG' },
    Zechariah: { id: 38, abbreviation: 'ZEC' },
    Malachi: { id: 39, abbreviation: 'MAL' },
    Matthew: { id: 40, abbreviation: 'MAT' },
    Mark: { id: 41, abbreviation: 'MRK' },
    Luke: { id: 42, abbreviation: 'LUK' },
    John: { id: 43, abbreviation: 'JHN' },
    Acts: { id: 44, abbreviation: 'ACT' },
    Romans: { id: 45, abbreviation: 'ROM' },
    '1 Corinthians': { id: 46, abbreviation: '1CO' },
    '2 Corinthians': { id: 47, abbreviation: '2CO' },
    Galatians: { id: 48, abbreviation: 'GAL' },
    Ephesians: { id: 49, abbreviation: 'EPH' },
    Philippians: { id: 50, abbreviation: 'PHP' },
    Colossians: { id: 51, abbreviation: 'COL' },
    '1 Thessalonians': { id: 52, abbreviation: '1TH' },
    '2 Thessalonians': { id: 53, abbreviation: '2TH' },
    '1 Timothy': { id: 54, abbreviation: '1TI' },
    '2 Timothy': { id: 55, abbreviation: '2TI' },
    Titus: { id: 56, abbreviation: 'TIT' },
    Philemon: { id: 57, abbreviation: 'PHM' },
    Hebrews: { id: 58, abbreviation: 'HEB' },
    James: { id: 59, abbreviation: 'JAS' },
    '1 Peter': { id: 60, abbreviation: '1PE' },
    '2 Peter': { id: 61, abbreviation: '2PE' },
    '1 John': { id: 62, abbreviation: '1JN' },
    '2 John': { id: 63, abbreviation: '2JN' },
    '3 John': { id: 64, abbreviation: '3JN' },
    Jude: { id: 65, abbreviation: 'JUD' },
    Revelation: { id: 66, abbreviation: 'REV' },
    '1 Esdras': { id: 67, abbreviation: '' },
    Tobit: { id: 68, abbreviation: '' },
    Judith: { id: 69, abbreviation: '' },
    Wisdom: { id: 70, abbreviation: '' },
    Sirach: { id: 71, abbreviation: '' },
    'Epistle of Jeremiah': { id: 72, abbreviation: '' },
    Baruch: { id: 73, abbreviation: '' },
    '1 Maccabees': { id: 74, abbreviation: '' },
    '2 Maccabees': { id: 75, abbreviation: '' },
    'Prayer of Manasseh': { id: 76, abbreviation: '' },
    '2 Esdras': { id: 77, abbreviation: '' },
    Susanna: { id: 78, abbreviation: '' },
    'Bel and Dragon': { id: 79, abbreviation: '' },
    Azariah: { id: 88, abbreviation: '' },
  };
